### ISSUE TITLE
the description says this code is private but the repository is public

### ISSUE THREAD

**Issue by joethorley** [propellerpdx/dataPipeline#14]

**Comment by mark-druffel** [comment]
Yes, this is a remaining question for us. This repo executes data models that are specific to our business so they won't be useful for anyone outside our company, but some of the wrapper functionality (AWS functions) will be. We may split this repo in the future in order to expose the wrappers and hide the business logic - a lot of the work is still too immature for us to plan that out so we aren't there yet....

**Comment by joethorley** [comment]
Just checking in case you were unknowingly exposing important proprietary code!
